"""
Base Code Generator Class
Abstract base class for all code generators
"""

from abc import ABC, abstractmethod
from datetime import datetime
import re


class CodeGenerator(ABC):
    """Abstract base class for code generators"""
    
    def __init__(self):
        self.generated_at = None
        self.project_name = None
        self.description = None
    
    @abstractmethod
    def generate(self, project_name, description, options):
        """
        Generate code based on requirements
        
        Args:
            project_name: Name of the project
            description: Detailed description
            options: Configuration options
        
        Returns:
            Dictionary with generated code files
        """
        pass
    
    def _create_header_comment(self, project_name, description):
        """Create standard header comment for generated files"""
        return f'''"""
{project_name}
{description}

Generated by: AI CodeGen Pro
Date: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
Version: 1.0.0
"""

'''
    
    def _to_snake_case(self, text):
        """Convert text to snake_case"""
        text = re.sub(r'[^\w\s]', '', text)
        text = re.sub(r'\s+', '_', text)
        return text.lower()
    
    def _to_camel_case(self, text):
        """Convert text to camelCase"""
        words = re.sub(r'[^\w\s]', '', text).split()
        if not words:
            return 'myProject'
        return words[0].lower() + ''.join(word.capitalize() for word in words[1:])
    
    def _to_pascal_case(self, text):
        """Convert text to PascalCase"""
        words = re.sub(r'[^\w\s]', '', text).split()
        return ''.join(word.capitalize() for word in words) if words else 'MyProject'
    
    def _generate_requirements(self, packages):
        """Generate requirements.txt from package list"""
        return '\n'.join(packages)
    
    def _generate_readme(self, project_name, description, sections=None):
        """Generate comprehensive README.md"""
        readme = f"""# {project_name}

{description}

## 🚀 Quick Start

### Prerequisites
- Python 3.8+
- pip package manager

### Installation
```bash
pip install -r requirements.txt
```

### Usage
```python
python main.py
```

## 📋 Features
{self._format_features_list(sections.get('features', [])) if sections else ''}

## 🛠️ Technology Stack
{self._format_tech_stack(sections.get('tech_stack', [])) if sections else ''}

## 📁 Project Structure
```
{sections.get('structure', 'See files in project directory') if sections else ''}
```

## 📊 Results
Results and visualizations will be saved in the project directory after execution.

## 🤝 Contributing
Feel free to fork and improve this generated project.

## 📝 License
This project was auto-generated and is free to use and modify.

## 🎯 Generated by
AI CodeGen Pro - {datetime.now().strftime("%Y-%m-%d")}
"""
        return readme
    
    def _format_features_list(self, features):
        """Format features as markdown list"""
        if not features:
            return "- Auto-generated code structure\n- Production-ready implementation"
        return '\n'.join(f"- {feature}" for feature in features)
    
    def _format_tech_stack(self, tech_stack):
        """Format technology stack as markdown list"""
        if not tech_stack:
            return "- Python 3.8+"
        return '\n'.join(f"- {tech}" for tech in tech_stack)
    
    def _add_docstring(self, text, indent=0):
        """Add properly formatted docstring"""
        indent_str = ' ' * indent
        return f'{indent_str}"""{text}"""'
    
    def _add_comment(self, text, inline=False):
        """Add comment to code"""
        return f"# {text}" if inline else f"# {text}\n" 